[package]
name = "advent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
petgraph = "0.5.0"
indexmap = "1.7.0"
hex = "0.4.3"
num = "0.4.0"
nom = "7.1.0"